name: Tests

on:
  push:
    branches: [ "trunk, master" ]
  pull_request:
    branches: [ "trunk" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest
    env:
      RUSTFLAGS: -D warnings
      RUSTDOCFLAGS: -D warnings
    strategy:
      matrix:
        toolchain:
          - stable
          - nightly
          - 1.31

    steps:
    - uses: actions/checkout@v3
    - run: rustup update ${{ matrix.toolchain }} && rustup default ${{ matrix.toolchain }}
    - name: Build
      run: cargo build --verbose
    - name: Test
      run: cargo test --verbose
    - name: Clippy
      run: cargo clippy --verbose
    - name: Doc
      run: cargo doc --verbose
    - name: Format
      run: cargo fmt --check --verbose